# Generated by Django 4.1.6 on 2023-04-02 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterModelTable(
            name='product',
            table='gallery',
        ),
    ]
