# Generated by Django 4.1.6 on 2023-04-02 21:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_order_orderproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 3, 7, 36, 819664)),
        ),
    ]
