# Generated by Django 4.1.6 on 2023-04-03 14:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_order_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='create_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 4, 3, 20, 8, 36, 137010)),
        ),
    ]
